baseURL = "https://jennshaggy.github.io/"
languageCode = "en-us"
title = "Jenn Shagrin"
theme = "PaperMod"

[params.profileMode]
enabled = true
imageUrl = "/images/profile.png"
imageTitle = "Jenn Shagrin"

[[menu.main]]
name = "Systems"
url = "/systems/"
weight = 10

[[menu.main]]
name = "Security"
url = "/security/"
weight = 20

[[menu.main]]
name = "Networking"
url = "/networking/"
weight = 30

[[menu.main]]
name = "Projects"
url = "/projects/"
weight = 40

[[menu.main]]
name = "Platforms & Training"
url = "/platforms/"
weight = 50

[[menu.main]]
name = "CIAT Portfolio"
url = "/ciat-portfolio/"
weight = 60




